# Generated by Django 6.1 on 2026-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
