# Generated by Django 6.1 on 2026-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
