# Generated by Django 6.1 on 2026-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_household_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
