# Generated by Django 6.1 on 2026-08-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0002_alter_household_name'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningRecipe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('nb_serving', models.DecimalField(decimal_places=2, max_digits=16)),
                ('planning_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_recipes', to='households.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_recipes', to='recipes.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
