# Generated by Django 6.1 on 2026-08-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0002_alter_household_name'),
        ('ingredients', '0002_ingredienttype_ingredientunit_seller_unitgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('shopping_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppings', to='households.household')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('units_bought', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='ingredients.ingredient')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='shoppings.itemcategory')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='shoppings.shopping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemToBuy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('units_to_buy', models.DecimalField(decimal_places=2, max_digits=16)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_to_buy', to='households.household')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_to_buy', to='ingredients.ingredient')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_to_buy', to='shoppings.itemcategory')),
                ('shopping_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_to_buy', to='shoppings.shoppingitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
