# Generated by Django 6.1 on 2026-08-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_household_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='ref_household',
        ),
        migrations.AddField(
            model_name='appuser',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='households.household'),
        ),
    ]
