# Generated by Django 6.1 on 2026-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_appuser_ref_household_appuser_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
